// <auto-generated />
using System;
using BusinessServiceTemplate.DataAccess.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessServiceTemplate.Database.Migrator.Migrations
{
    [DbContext(typeof(TestSelectionRepositoryContext))]
    [Migration("20230416121633_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SC_Panels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Panel1",
                            Name = "Panel1",
                            Price = 10.01m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Panel2",
                            Name = "Panel2",
                            Price = 20.01m
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel_Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PanelId")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.HasIndex("TestId");

                    b.ToTable("SC_Panel_Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PanelId = 1,
                            TestId = 1
                        },
                        new
                        {
                            Id = 2,
                            PanelId = 1,
                            TestId = 2
                        },
                        new
                        {
                            Id = 3,
                            PanelId = 2,
                            TestId = 1
                        },
                        new
                        {
                            Id = 4,
                            PanelId = 1,
                            TestId = 2
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SC_Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "test1",
                            Name = "test1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "test2",
                            Name = "test2"
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_TestSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SC_TestSelections");
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel_Test", b =>
                {
                    b.HasOne("BusinessServiceTemplate.DataAccess.Entities.SC_Panel", "Panels")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessServiceTemplate.DataAccess.Entities.SC_Test", "Tests")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panels");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
