// <auto-generated />
using BusinessServiceTemplate.DataAccess.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BusinessServiceTemplate.Database.Migrator.Migrations
{
    [DbContext(typeof(TestSelectionRepositoryContext))]
    [Migration("20230419041012_addedpropertyformapping")]
    partial class addedpropertyformapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("DescriptionVisibility")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PriceVisibility")
                        .HasColumnType("boolean");

                    b.Property<int>("TestSelectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestSelectionId");

                    b.ToTable("SC_Panels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Panel1",
                            DescriptionVisibility = true,
                            Name = "Panel1",
                            Price = 10.01m,
                            PriceVisibility = true,
                            TestSelectionId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Panel2",
                            DescriptionVisibility = true,
                            Name = "Panel2",
                            Price = 20.01m,
                            PriceVisibility = true,
                            TestSelectionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Panel3",
                            DescriptionVisibility = true,
                            Name = "Panel3",
                            Price = 30.01m,
                            PriceVisibility = true,
                            TestSelectionId = 1
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel_Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PanelId")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.HasIndex("TestId");

                    b.ToTable("SC_Panel_Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PanelId = 1,
                            TestId = 1,
                            Visibility = true
                        },
                        new
                        {
                            Id = 2,
                            PanelId = 1,
                            TestId = 2,
                            Visibility = false
                        },
                        new
                        {
                            Id = 3,
                            PanelId = 2,
                            TestId = 1,
                            Visibility = true
                        },
                        new
                        {
                            Id = 4,
                            PanelId = 1,
                            TestId = 2,
                            Visibility = false
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("DescriptionVisibility")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SC_Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "test1",
                            DescriptionVisibility = true,
                            Name = "test1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "test2",
                            DescriptionVisibility = true,
                            Name = "test2"
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_TestSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("DescriptionVisibility")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SC_TestSelections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test Selection 1",
                            DescriptionVisibility = true,
                            Name = "Test Selection 1",
                            SpecialityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test Selection 2",
                            DescriptionVisibility = false,
                            Name = "Test Selection 2",
                            SpecialityId = 2
                        });
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel", b =>
                {
                    b.HasOne("BusinessServiceTemplate.DataAccess.Entities.SC_TestSelection", "TestSelection")
                        .WithMany("Panels")
                        .HasForeignKey("TestSelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSelection");
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_Panel_Test", b =>
                {
                    b.HasOne("BusinessServiceTemplate.DataAccess.Entities.SC_Panel", "Panels")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessServiceTemplate.DataAccess.Entities.SC_Test", "Tests")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panels");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("BusinessServiceTemplate.DataAccess.Entities.SC_TestSelection", b =>
                {
                    b.Navigation("Panels");
                });
#pragma warning restore 612, 618
        }
    }
}
